# Generated by Django 3.2.6 on 2021-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('editor_text', models.TextField()),
            ],
            options={
                'db_table': 'editor',
            },
        ),
    ]
