# Generated by Django 3.2.6 on 2021-08-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20210809_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
